spring:
  application:
    name: Spring batch examples
  datasource:
    url: jdbc:h2:mem:testdb
    # jdbc:h2:file:/data/demo
    driverClassName: org.h2.Driver
    username: sa
    password: password

logging.level:
  root: ERROR
  com:
    prabwork:
      springbatch:
        config: INFO
